/**
 * OrgTree — Organizational Directory & Hierarchy Visualization
 *
 * Copyright (c) 2025 OJD Technical Solutions (Omar Davis)
 * Toronto, Ontario, Canada
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of OrgTree. OrgTree is free software: you can redistribute
 * it and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OrgTree is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with OrgTree. If not, see <https://www.gnu.org/licenses/>.
 *
 * Commercial licensing is available. Contact OJD Technical Solutions for details.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check server and database connectivity
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Server is healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example ok */
              status?: string;
              /** Format: date-time */
              timestamp?: string;
              /** @example connected */
              database?: string;
              /** @example production */
              environment?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register new user
     * @description Create a new user account. Rate limited to 5 requests per 15 minutes.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        400: components['responses']['BadRequest'];
        /** @description Rate limit exceeded */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User login
     * @description Authenticate and receive JWT token. Rate limited to 5 requests per 15 minutes.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        400: components['responses']['BadRequest'];
        /** @description Invalid credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Rate limit exceeded */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Get the authenticated user's profile
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change password
     * @description Change the authenticated user's password
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description Password changed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message?: string;
              user?: components['schemas']['User'];
            };
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List organizations
     * @description Get all organizations the user has access to
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of organizations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Organization'][];
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    /**
     * Create organization
     * @description Create a new organization. The creator becomes the owner.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
          };
        };
      };
      responses: {
        /** @description Organization created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Organization'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * Get organization
     * @description Get organization details
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Organization details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Organization'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
        404: components['responses']['NotFound'];
      };
    };
    /**
     * Update organization
     * @description Update organization name. Requires editor role or above.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
          };
        };
      };
      responses: {
        /** @description Organization updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Organization'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    /**
     * Delete organization
     * @description Delete organization and all its data. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Organization deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/share': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * Get share settings
     * @description Get public sharing configuration. Requires viewer role or above.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Share settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ShareSettings'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    /**
     * Update share settings
     * @description Enable/disable public sharing. Requires admin role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            isPublic: boolean;
          };
        };
      };
      responses: {
        /** @description Share settings updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ShareSettings'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/share/regenerate': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Regenerate share token
     * @description Generate a new share URL, invalidating the old one. Requires admin role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description New share token generated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ShareSettings'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/departments': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * List departments
     * @description Get all departments in an organization
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of departments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Department'][];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /**
     * Create department
     * @description Create a new department. Requires editor role or above.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            description?: string;
            /**
             * Format: uuid
             * @description Parent department ID for nested hierarchy
             */
            parentId?: string | null;
          };
        };
      };
      responses: {
        /** @description Department created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Department'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/departments/{deptId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
        deptId: string;
      };
      cookie?: never;
    };
    /**
     * Get department
     * @description Get department details
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          deptId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Department details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Department'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    /**
     * Update department
     * @description Update department details. Requires editor role or above.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          deptId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            description?: string;
            /** Format: uuid */
            parentId?: string | null;
          };
        };
      };
      responses: {
        /** @description Department updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Department'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    /**
     * Delete department
     * @description Delete department and optionally its children. Requires editor role or above.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          deptId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Department deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/departments/{deptId}/people': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deptId: string;
      };
      cookie?: never;
    };
    /**
     * List people in department
     * @description Get all people in a department
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          deptId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of people */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Person'][];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /**
     * Create person
     * @description Add a new person to a department. Requires editor role or above.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          deptId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            title?: string;
            /** Format: email */
            email?: string;
            phone?: string;
          };
        };
      };
      responses: {
        /** @description Person created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Person'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/people/{personId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        personId: string;
      };
      cookie?: never;
    };
    /**
     * Get person
     * @description Get person details
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          personId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Person details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Person'];
          };
        };
        401: components['responses']['Unauthorized'];
        404: components['responses']['NotFound'];
      };
    };
    /**
     * Update person
     * @description Update person details. Requires editor role or above.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          personId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            title?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            /**
             * Format: uuid
             * @description Move person to different department
             */
            departmentId?: string;
          };
        };
      };
      responses: {
        /** @description Person updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Person'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    /**
     * Delete person
     * @description Remove person from organization. Requires editor role or above.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          personId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Person deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/people/{personId}/move': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        personId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Move person
     * @description Move person to a different department. Requires editor role or above.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          personId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            departmentId: string;
          };
        };
      };
      responses: {
        /** @description Person moved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Person'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * List members
     * @description Get all members of an organization. Requires admin role.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Organization members */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              owner?: {
                userId?: string;
                userName?: string;
                userEmail?: string;
                /** @enum {string} */
                role?: 'owner';
              };
              members?: components['schemas']['Member'][];
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /**
     * Add member by user ID
     * @description Add a user to the organization. Requires admin role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            userId: string;
            /** @enum {string} */
            role: 'viewer' | 'editor' | 'admin';
          };
        };
      };
      responses: {
        /** @description Member added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/members/by-email': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add member by email
     * @description Add a user by email. Returns success:false if user not found. Requires admin role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: 'viewer' | 'editor' | 'admin';
          };
        };
      };
      responses: {
        /** @description User not found (can send invitation instead) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example false */
              success?: boolean;
              /** @example user_not_found */
              error?: string;
            };
          };
        };
        /** @description Member added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example true */
              success?: boolean;
              member?: components['schemas']['Member'];
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/members/{memberId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
        memberId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Update member role
     * @description Change a member's role. Requires admin role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          memberId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            role: 'viewer' | 'editor' | 'admin';
          };
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    /**
     * Remove member
     * @description Remove a member from the organization. Requires admin role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          memberId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Member removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * List invitations
     * @description Get pending invitations for an organization. Requires admin role.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of invitations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invitation'][];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /**
     * Send invitation
     * @description Send an email invitation to join the organization. Requires admin role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: 'viewer' | 'editor' | 'admin';
          };
        };
      };
      responses: {
        /** @description Invitation sent */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invitation'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/invitations/{invitationId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
        invitationId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Cancel invitation
     * @description Cancel a pending invitation. Requires admin role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
          invitationId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Invitation cancelled */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invitations/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    /**
     * Get invitation by token
     * @description Get invitation details. No authentication required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          token: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Invitation details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invitation'];
          };
        };
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invitations/{token}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept invitation
     * @description Accept an invitation and join the organization
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          token: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Invitation accepted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message?: string;
              organization?: components['schemas']['Organization'];
            };
          };
        };
        /** @description Invalid or expired invitation */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invitations/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check email service status
     * @description Check if email invitations are configured
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Email service status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              emailConfigured?: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/search': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * Full-text search
     * @description Search across departments and people with FTS5
     */
    get: {
      parameters: {
        query: {
          /** @description Search query */
          q: string;
          /** @description Filter by entity type */
          type?: 'all' | 'departments' | 'people';
          limit?: number;
          offset?: number;
        };
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Search results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SearchResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/search/autocomplete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * Autocomplete suggestions
     * @description Fast prefix-based suggestions for search
     */
    get: {
      parameters: {
        query: {
          /** @description Partial search query */
          q: string;
          limit?: number;
        };
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Autocomplete suggestions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              suggestions?: {
                text?: string;
                /** @enum {string} */
                type?: 'department' | 'person';
              }[];
            };
          };
        };
        401: components['responses']['Unauthorized'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/people/bulk-delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk delete people
     * @description Delete multiple people at once. Max 100 items. Requires editor role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            personIds: string[];
          };
        };
      };
      responses: {
        /** @description Bulk delete result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BulkResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/people/bulk-move': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk move people
     * @description Move multiple people to a department. Max 100 items. Requires editor role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            personIds: string[];
            /** Format: uuid */
            targetDepartmentId: string;
          };
        };
      };
      responses: {
        /** @description Bulk move result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BulkResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/people/bulk-edit': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Bulk edit people
     * @description Update fields on multiple people. Max 100 items. Requires editor role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            personIds: string[];
            updates: {
              title?: string;
              /** Format: uuid */
              departmentId?: string;
            };
          };
        };
      };
      responses: {
        /** @description Bulk edit result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BulkResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/departments/bulk-delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk delete departments
     * @description Delete multiple departments. Max 100 items. Requires editor role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            departmentIds: string[];
          };
        };
      };
      responses: {
        /** @description Bulk delete result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BulkResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/departments/bulk-edit': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Bulk edit departments
     * @description Update fields on multiple departments (mainly re-parenting). Max 100 items. Requires editor role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            departmentIds: string[];
            updates: {
              /**
               * Format: uuid
               * @description Set to null for root level
               */
              parentId?: string | null;
            };
          };
        };
      };
      responses: {
        /** @description Bulk edit result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BulkResult'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    /**
     * Get audit logs
     * @description Get audit logs for an organization. Requires admin role.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          /** @description Pagination cursor from previous response */
          cursor?: string;
          actionType?: 'created' | 'updated' | 'deleted' | 'settings_changed';
          entityType?: 'department' | 'person' | 'member' | 'org' | 'invitation';
          startDate?: string;
          endDate?: string;
        };
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Audit logs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              logs?: components['schemas']['AuditLog'][];
              nextCursor?: string | null;
              hasMore?: boolean;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all audit logs (superuser)
     * @description Get audit logs across all organizations. Requires superuser role.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by organization */
          orgId?: string;
          limit?: number;
          cursor?: string;
          actionType?: 'created' | 'updated' | 'deleted' | 'settings_changed';
          entityType?: 'department' | 'person' | 'member' | 'org' | 'invitation';
          startDate?: string;
          endDate?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Audit logs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              logs?: components['schemas']['AuditLog'][];
              nextCursor?: string | null;
              hasMore?: boolean;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations/{orgId}/import': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orgId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import data
     * @description Import departments and people from parsed CSV data. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          orgId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            data: {
              /** @description Hierarchical path (e.g., /Finance/Accounting) */
              path: string;
              /** @enum {string} */
              type: 'department' | 'person';
              name: string;
              title?: string;
              email?: string;
              phone?: string;
              description?: string;
            }[];
          };
        };
      };
      responses: {
        /** @description Import result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              success?: boolean;
              departmentsCreated?: number;
              peopleCreated?: number;
            };
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/org/{shareToken}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        shareToken: string;
      };
      cookie?: never;
    };
    /**
     * Get public organization
     * @description Get organization data via public share token. No authentication required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          shareToken: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Public organization data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: string;
              name?: string;
              /** Format: date-time */
              createdAt?: string;
              departments?: (components['schemas']['Department'] & {
                people?: components['schemas']['Person'][];
              })[];
            };
          };
        };
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/invitation/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    /**
     * Get public invitation
     * @description Get invitation details by token. No authentication required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          token: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Invitation details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invitation'];
          };
        };
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all users
     * @description Get all users in the system. Requires superuser role.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of users */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'][];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    put?: never;
    /**
     * Create user
     * @description Create a new user with temporary password. Requires superuser role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: 'user' | 'superuser';
          };
        };
      };
      responses: {
        /** @description User created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user?: components['schemas']['User'];
              temporaryPassword?: string;
            };
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    /**
     * Get user
     * @description Get user details. Requires superuser role.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
        404: components['responses']['NotFound'];
      };
    };
    /**
     * Update user
     * @description Update user name/email. Requires superuser role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
            /** Format: email */
            email?: string;
          };
        };
      };
      responses: {
        /** @description User updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        400: components['responses']['BadRequest'];
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    /**
     * Delete user
     * @description Delete a user. Cannot delete self. Requires superuser role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cannot delete self */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/role': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Change user role
     * @description Change user's system role. Cannot change own role. Requires superuser role.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            role: 'user' | 'superuser';
          };
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        /** @description Cannot change own role */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{userId}/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset user password
     * @description Reset user's password to a temporary one. Rate limited. Requires superuser role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Password reset */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              message?: string;
              temporaryPassword?: string;
            };
          };
        };
        401: components['responses']['Unauthorized'];
        403: components['responses']['Forbidden'];
        /** @description Rate limit exceeded */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @example Error description */
      message?: string;
    };
    User: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: 'user' | 'superuser';
      /** Format: date-time */
      createdAt?: string;
      mustChangePassword?: boolean;
    };
    AuthResponse: {
      /** @description JWT access token */
      token?: string;
      user?: components['schemas']['User'];
    };
    Organization: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** Format: uuid */
      createdById?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      /**
       * @description Current user's role in this organization
       * @enum {string}
       */
      role?: 'owner' | 'admin' | 'editor' | 'viewer';
    };
    Department: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      organizationId?: string;
      /** Format: uuid */
      parentId?: string | null;
      name?: string;
      description?: string | null;
      sortOrder?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Person: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      departmentId?: string;
      name?: string;
      title?: string | null;
      /** Format: email */
      email?: string | null;
      phone?: string | null;
      sortOrder?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Member: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      userId?: string;
      userName?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: 'viewer' | 'editor' | 'admin';
      /** Format: date-time */
      createdAt?: string;
    };
    Invitation: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: 'viewer' | 'editor' | 'admin';
      /** @enum {string} */
      status?: 'pending' | 'accepted' | 'expired' | 'cancelled';
      /** Format: date-time */
      expiresAt?: string;
      /** Format: date-time */
      createdAt?: string;
      organizationName?: string;
      invitedByName?: string;
    };
    AuditLog: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      organizationId?: string;
      /** Format: uuid */
      actorId?: string;
      actorName?: string;
      actorEmail?: string;
      /** @enum {string} */
      actionType?: 'created' | 'updated' | 'deleted' | 'settings_changed';
      /** @enum {string} */
      entityType?: 'department' | 'person' | 'member' | 'org' | 'invitation';
      entityId?: string;
      entityName?: string;
      details?: Record<string, never>;
      /** Format: date-time */
      createdAt?: string;
    };
    SearchResult: {
      results?: {
        /** @enum {string} */
        type?: 'department' | 'person';
        id?: string;
        name?: string;
        /** @description Name with matched terms highlighted */
        highlight?: string;
        title?: string | null;
        email?: string | null;
        departmentId?: string | null;
        departmentName?: string | null;
      }[];
      total?: number;
      hasMore?: boolean;
    };
    BulkResult: {
      success?: boolean;
      deletedCount?: number;
      updatedCount?: number;
      movedCount?: number;
      failedCount?: number;
      deleted?: string[];
      updated?: string[];
      failed?: {
        id?: string;
        error?: string;
      }[];
    };
    ShareSettings: {
      isPublic?: boolean;
      shareToken?: string | null;
      /** Format: uri */
      shareUrl?: string | null;
    };
  };
  responses: {
    /** @description Authentication required */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "message": "Access token required"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Insufficient permissions */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "message": "Access denied"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "message": "Resource not found"
         *     }
         */
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
